### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by liggiorgio** [CsUnipa/SistemiInformativiAziendali#1]
Bisogna inserire le dispense e i file forniti dal docente del corso

**Comment by dlion** [comment]
Ovviamente, dispense e files che sono reperibili solo una volta che la materia è stata caricata sul portale...

**Comment by dlion** [comment]
Ok sono riuscito a registrarmi e a scaricare il materiale.
https://github.com/CsUnipa/SistemiInformativiAziendali/commit/5850874afd9c3e14e30096b64838257e13a12bb3
